spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://database.c50xqnmxv90m.ap-southeast-1.rds.amazonaws.com:3306/blog?&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: warn
    com.bubble: info
  file: log/blog-pro.log 
server:
  port: 8081  